# Generated by Django 5.0.7 on 2024-08-04 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passing_year',
        ),
    ]
